---
- hosts: vmware-workstation-host
  tasks:
    - name: "Clone KMS server"
      vmware_workstation_clone:
        targetVM: "42"
        newname: "Hello_World"
        user: "workstation-api-user"
        pass: "workstation-api-password"
        apiurl: "http://127.0.0.1:8697/api/vms"